### ISSUE TITLE
[CHORE] train 코드 수정

### ISSUE THREAD

**Issue by yunguks** [boostcampaitech5/level1_imageclassification-cv-02#24]
## Background
- train, inference 시 오류가나는 parameter수정
- best 모델 저장 기준을 f1_score로
    
## Todo
- [x] argpaser resize 수정
- [x] best_f1_score 추가
- [x] Base augmentation 수정
