### ISSUE TITLE
[CHORE] inference 코드 및 dataset 수정

### ISSUE THREAD

**Issue by yunguks** [boostcampaitech5/level1_imageclassification-cv-02#39]
## Background
- inference 코드에 옵션추가
- dataset num_classes 수정
    
## Todo
- [x] inference augmenataion 추가
- [x] inference output.csv 이름 추가
- [x] dataset num_classes 변경
