### ISSUE TITLE
[FEAT] SwinVIT Model 추가

### ISSUE THREAD

**Issue by daehun1102** [boostcampaitech5/level1_imageclassification-cv-02#55]
## Background
- 성능 좋았던 SwinVIT Model 추가
    
## Todo
- [x] swin_s3_small_224 추가
- [x] swin_small_patch4_window7_224 추가
- [x] swin_base_patch4_window7_224 추가
